// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Sun Feb 04 22:25:43 2024

MEMORY MEMORY_inst
(
	.MEM_ADDRESS(MEM_ADDRESS_sig) ,	// input [15:0] MEM_ADDRESS_sig
	.MEM_DATA(MEM_DATA_sig) ,	// input [15:0] MEM_DATA_sig
	.MEMWRITE(MEMWRITE_sig) ,	// input  MEMWRITE_sig
	.CLK(CLK_sig) ,	// input  CLK_sig
	.MEM_OUT(MEM_OUT_sig) 	// output [15:0] MEM_OUT_sig
);

